
// MANGA
export const GET_ALL_MANGA = "GET_ALL_MANGA";
export const GET_ALL_MANGA_LOADING = "GET_ALL_MANGA_LOADING";

// ERROR
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";